{% set data = load_setup_py_data() %}


package:
  name: panno
  version: {{ data.version }}


source:
  - path: ../


build:
  include_recipe: True
  entry_points:
    - panno = panno.cli:main


requirements:
  build:
    - python ==3.8
    - setuptools
  
  run:
    - python ==3.8
    - pandas >=1.3.2
    - numpy >=1.19.5
    - pyranges ==0.0.117


test:
  commands:
    - panno -h
  imports:
    - panno


about:
  home: {{ data.url }}
  license: MOZILLA
  license_file: LICENSE
  license_family: MOZILLA
  
  summary: {{ data.description }}
  description: PAnno reports drug responses and prescribing recommendations by parsing the germline variant call format (VCF) file from NGS and the population to which the individual belongs. PAnno provides an end-to-end clinical pharmacogenomics decision support solution by resolving, annotating, and reporting germline variants in individuals.
  doc_url: {{ data.url }}
  dev_url: {{ data.url }}